import { expect, test } from 'bun:test';
import { CreateWallet } from '../../application/create-wallet';
import { handleUserCreated } from '../../messaging/user-created-consumer';

// Independent consumer baseline, deliberately not generated by the User mapper.
const baseline =
  '{"type":"user.created","version":1,"source":"user","eventId":"event-42","occurredAt":"2026-09-30T12:00:00Z","correlationId":"request-42","causationId":"command-42","data":{"userId":"user-42"}}';

test('the consumer validates version and envelope before any transaction starts', async () => {
  const create = new CreateWallet({
    run: () => {
      throw new Error('business behavior must not run');
    },
  });
  for (const body of [
    '{',
    baseline.replace('"version":1', '"version":2'),
    baseline.replace('"userId":"user-42"', '"email":"private"'),
  ]) {
    expect(await handleUserCreated(body, create)).toEqual({
      accepted: false,
      reason: 'invalid-or-unsupported-user-created',
    });
  }
});

test('baseline and additive deliveries supply their own identity and correlation context to the plain use case', async () => {
  const recorded: unknown[] = [];
  const wallets: unknown[] = [];
  const create = new CreateWallet({
    run: (operation) =>
      operation({
        claim: (event) => {
          recorded.push(event);
          return Promise.resolve(true);
        },
        insertIfAbsent: (wallet) => {
          wallets.push({
            userId: wallet.getProps().userId,
            balance: wallet.getProps().balance,
          });
          return Promise.resolve();
        },
      }),
  });
  const second = baseline
    .replace('event-42', 'event-43')
    .replace('request-42', 'request-43')
    .replace('"version":1', '"version":1,"optional":true');
  await Promise.all([
    handleUserCreated(baseline, create),
    handleUserCreated(second, create),
  ]);
  expect(recorded).toEqual([
    {
      eventId: 'event-42',
      userId: 'user-42',
      correlationId: 'request-42',
      causationId: 'command-42',
      occurredAt: '2026-09-30T12:00:00Z',
    },
    {
      eventId: 'event-43',
      userId: 'user-42',
      correlationId: 'request-43',
      causationId: 'command-42',
      occurredAt: '2026-09-30T12:00:00Z',
    },
  ]);
  expect(wallets).toEqual([
    { userId: 'user-42', balance: 0 },
    { userId: 'user-42', balance: 0 },
  ]);
});
